name: "Docker Build Tag Push to GCR"
author: "Sean McGrath"
description: "Build, tag, and push images to Google Container Registry"

inputs:
  registry:
    description: "Registry URL"
    required: false
    default: "gcr.io"
  image:
    description: "Docker image name"
    required: true
  version_tag:
    description: "Docker image version tag"
    required: false
  environment:
    description: "Environment name"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
